name: Testing install

on:
  push:

jobs:
  install:
    name: Install script
    strategy:
      matrix:
        os: [windows-latest]
#        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - run: curl --version
#      - run: curl -w '%{json}' -sL -H "Accept:application/json" -o foo https://github.com/golangci/golangci-lint/releases/v1.59.1
#      - run: curl -w '%{http_code}' -sL -H "Accept:application/json" -o bar https://github.com/golangci/golangci-lint/releases/v1.59.1
#      - run: curl -w '%{json}' -sL -H "Accept:application/json" -o bar https://github.com/golangci/golangci-lint/releases/v1.59.1 | jq
#      - run: curl -SfL "https://raw.githubusercontent.com/golangci/misspell/master/install-misspell.sh" | sh -s -- -d -b "./temp-misspell" v0.6.0
#      - run: curl -SfL "https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh" | sh -s -- -d -b "./temp-gcil" v1.59.1
      - run: cat ./install.sh | sh -s -- -d -b "./temp-gcil" v1.59.2
