name: Testing env (workflow_dispatch) Bench

on:
  workflow_dispatch:
    inputs:
      linter:
        description: 'Linter name'
        required: true
        type: string
      value:
        description: 'Pull request number'
        required: true
        type: number
      version:
        description: 'Golangci-lint version'
        required: true
        default: 'v1.59.1'
        type: string

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: 'Print the input data'
        run: echo 'Inputs are ${{ toJSON(inputs) }}'
      - name: 'Print the github.event.inputs data'
        run: echo 'Inputs are ${{ toJSON(github.event.inputs) }}'
