name: Testing docker gha output

on:
  push:

defaults:
  run:
    working-directory: myapp

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - run: docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.58.0 golangci-lint run --out-format=github-actions
        env:
            ACTIONS_STEP_DEBUG: true
        working-directory: myapp
