name: Testing misspell

on:
  push:

jobs:
  install:
    name: Install script
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
#      - run: curl -SfL https://raw.githubusercontent.com/golangci/misspell/master/install-misspell.sh | sh -s -- -b "./temp-misspell" v0.5.2
      - run: cat ./install-misspell.sh | sh -s -- -d -b "./temp-misspell" v0.5.2
