name: Testing env

on:
  push:
    branches:
      - temp # just to disable the workflow

defaults:
  run:
    working-directory: dirA

jobs:
  dump_contexts_to_log:
    runs-on: ${{ matrix.os }}
    env:
      CGO_ENABLED: 0
    defaults:
      run:
        working-directory: dirB

    strategy:
      matrix:
        go-version: [ stable ]
        os: [ubuntu-latest] # [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Env
        run: env

      - name: WD 02 (${{ github.working-directory }})
        run: pwd
        working-directory: dirC

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
