name: Testing env

on:
  push:
    branches:
      - temp # just to disable the workflow

defaults:
  run:
    working-directory: myapp

jobs:
  linting-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - uses: golangci/golangci-lint-action@9a0aa6bf4265e350a2a7de36811bafe5075198a8
        with:
          version: v1.57
          working-directory: myapp
#          annotations: false
