name: Testing env

on:
  push:

defaults:
  run:
    working-directory: myapp

jobs:
  linting-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
#      - run: git pull --unshallow
      - run: git pull --deepen=3
      - run: git log --graph --pretty=tformat:'%Cred%h%Creset %Cblue%G?%Creset -%C(auto)%d%Creset %s %Cgreen(%an %ar)%Creset' --branches --remotes

#      - uses: golangci/golangci-lint-action@b556f25b3c7399b6dad72f47062098ff1b36e060
#        with:
#          version: v1.57
#          working-directory: myapp
