name: Testing env

on:
  push:

defaults:
  run:
    working-directory: myapp

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - uses: golangci/golangci-lint-action@3e73387f99e37887967a54cad4d98dd8ea791352
        with:
          version: v1.57
          working-directory: myapp
          annotations: false
