name: Testing env

on:
  push:

defaults:
  run:
    working-directory: myapp

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - uses: golangci/golangci-lint-action@533e49f5e2366a9e5d943497c006a8de3dc81ff4
        with:
          version: v1.58
          install-mode: 'goinstall'
          working-directory: myapp
          annotations: true
