name: Testing env

on:
  push:

defaults:
  run:
    working-directory: myapp

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - uses: golangci/golangci-lint-action@b3d3481ce40b14ddc14786e285ba44a2c5ce27c5
        with:
          version: 37c3a18f078536a55bdcc71aae75f55591ca6431
          install-mode: 'goinstall'
          working-directory: myapp
          annotations: false
