name: Testing env

on:
  push:

defaults:
  run:
    working-directory: myapp

jobs:
  linting-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - uses: golangci/golangci-lint-action@3ceaf4f5c7d8f161dbddc723afe50bba9ca29fa5
        with:
          version: v1.57
          working-directory: myapp
#          annotations: false
