name: Testing env

on:
  push:

defaults:
  run:
    working-directory: myapp

jobs:
  linting-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - uses: golangci/golangci-lint-action@a89ebf9a5335c964188fe71d5f589c615a2660ba
        with:
          version: v1.57
          working-directory: myapp
          annotations: false
