name: golangci-lint (multi OS)

#on:
#  pull_request:
#  push:
#    branches:
#      - "main"
#      - "master"

on:
  workflow_dispatch:
    inputs:
      repository:
        description: "Repository name (owner/repo)"
        type: string
        default: 'git-town/git-town'

jobs:
  golangci-lint:
    strategy:
      matrix:
        go-version: [ stable, oldstable ]
        os: [ubuntu-latest, macos-latest, windows-latest]
    uses: ./.github/workflows/.golangci-lint-reusable.yml
    with:
      os: ${{ matrix.os }}
      go-version: ${{ matrix.go-version }}
      repository: ${{ inputs.repository }}
      golangci-lint-version: 'v1.59.1'
